name: 'ğŸŒ Terraform Automation'

on:
  push:

# env:
  # TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}} # dev
  # ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}} # dev
  # ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  # ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  # ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ğŸ§© HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
      
      - name: ğŸ”‘ Login to Azure
        id : az-login
        run : az login  

      - name: ğŸ—ï¸ Terraform 
        id: init
        run: |
            terraform init -input=false
            # terraform destroy -input=false -auto-approve
            terraform plan -out=tfplan -input=false
            terraform apply -input=false -auto-approve tfplan